const cafes = [
  {id:1,name:'Aruba Cafe',area:'Park West',address:'<br>9824 W Northern Ave <br>Peoria, AZ 85345',rating:4.9,distance:4.0,tags:['work','roaster'],type:'Tropical island cafe',hours:'Open until 11:00 PM',image:'linear-gradient(145deg,rgba(28,37,32,.16),rgba(28,37,32,.25)),url(https://s3-media0.fl.yelpcdn.com/bphoto/5YU55iS8wskOwR-mNi_XSQ/348s.jpg)',pos:[25,28],description:'Your Paradise awaits at Aruba Cafe, Where we serve a range of coffee, teas, juices, and handcraft waffles to keep your mood naturally uplifted.'},
  
  {id:2,name:'Wild Pine Coffee & Cocktails',area:'Lake Pleasant',address:'<br>20340 N Lake Pleasant Rd #110 <br>Peoria, AZ 85382',rating:4.8,distance:7.5,tags:['work','brunch'],type:'All-day café',hours:'Open until 5:00 PM',image:'linear-gradient(145deg,rgba(28,37,32,.12),rgba(28,37,32,.24)),url(https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=700&q=80)',pos:[60,20],description:'A sunny all-day café serving bright coffee, generous brunch, and plenty of room to settle in.'},
  
  {id:3,name:'House of Honey',area:'Riverside',address:'<br>9163 W Union Hills Dr ste 116<br>Peoria, AZ 85382',rating:4.8,distance:6.7,tags:['outdoor','roaster'],type:'Neighborhood café',hours:'Open until 3:00 PM',image:'linear-gradient(145deg,rgba(28,37,32,.1),rgba(28,37,32,.28)),url(https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ31i7I2Pyj9J0k-ZC_X-pTLjPpC7A6DJLg1sYeY0b6TuJR5L4qHxordQ&s=10)',pos:[35,63],description:'Thoughtfully made coffee with an easygoing patio and a small shelf of local goods.'},
  
  {id:4,name:'808 Social AZ',area:'Riverside',address:'<br>1808 Social AZ, 8435 W Peoria Ave <br>Peoria, AZ 85345',rating:4.9,distance:0.3,tags:['outdoor','brunch'],type:'Bakery & café',hours:'Open until 4:00 PM',image:'linear-gradient(145deg,rgba(28,37,32,.1),rgba(28,37,32,.28)),url(https://s3-media0.fl.yelpcdn.com/bphoto/LCFjYU-Q-JqjmAsvjXJDcA/348s.jpg)',pos:[70,67],description:'A waterside bakery café where slow breakfasts and long conversations are encouraged.'},
  
  {id:5,name:'TheBrewBox Coffee Company',area:'Midtown',address:'<br>7518 W Thunderbird Rd Ste 4 <br>Peoria, AZ 85381',rating:4.7,distance:3.2,tags:['work'],type:'Cozy café',hours:'Open until 6:00 PM',image:'linear-gradient(145deg,rgba(28,37,32,.08),rgba(28,37,32,.28)),url(https://s3-media0.fl.yelpcdn.com/bphoto/3kbJ7BwqS4H1BR36wNAMfA/348s.jpg)',pos:[16,78],description:'A bookish café with excellent pour-over and communal work tables in a restored storefront.'},
  
  {id:6,name:'Cousins Coffee Co.',area:'Arts District',address:'<br>6750 W Olive Ave Suite 106 <br>Peoria, AZ 85345',rating:5.0,distance:2.5,tags:['outdoor','brunch'],type:'Cousins owned café',hours:'Open until 2:00 PM',image:'linear-gradient(145deg,rgba(28,37,32,.06),rgba(28,37,32,.28)),url(https://tb-static.uber.com/prod/image-proc/processed_images/8c07b5f840cb2aed65c024dab6c00a36/c86a2d4dc3dc568dc3ddf7b096104ac3.jpeg)',pos:[80,43],description:'Seasonal plates, house-made pastries, and a leafy courtyard in the heart of the district.'}
];
const state={filter:'all',search:'',sort:'recommended',onlySaved:false,saved:new Set(JSON.parse(localStorage.getItem('pour-saved')||'[]'))};
const grid=document.querySelector('#cafeGrid'), pins=document.querySelector('#mapPins'), count=document.querySelector('#resultCount'), empty=document.querySelector('#emptyState'), toast=document.querySelector('#toast');
function filtered(){let result=cafes.filter(c=>{const text=`${c.name} ${c.type} ${c.tags.join(' ')}`.toLowerCase();return (!state.onlySaved||state.saved.has(c.id))&&(state.filter==='all'||c.tags.includes(state.filter))&&text.includes(state.search.toLowerCase())});return result.sort((a,b)=>state.sort==='rating'?b.rating-a.rating:state.sort==='distance'?a.distance-b.distance:a.id-b.id)}
function render(){const result=filtered();count.textContent=`${result.length} ${result.length===1?'place':'places'} to explore`;grid.innerHTML=result.map(c=>`<article class="cafe-card"><div class="card-image" style="background-image:${c.image}"><span class="tag">${c.type}</span><button class="save-card ${state.saved.has(c.id)?'saved':''}" data-save="${c.id}" aria-label="Save ${c.name}">${state.saved.has(c.id)?'♥':'♡'}</button></div><div class="card-body" data-details="${c.id}"><div class="card-meta"><span class="rating">★ ${c.rating}</span><span>${c.distance} mi away</span></div><h3>${c.name}</h3><p class="address">${c.address}</p></div></article>`).join('');pins.innerHTML=result.map(c=>`<button class="pin" style="left:${c.pos[0]}%;top:${c.pos[1]}%" data-details="${c.id}" aria-label="View ${c.name}"></button>`).join('');empty.hidden=result.length>0;grid.hidden=result.length===0;document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>toggleSave(+b.dataset.save));document.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>showDetails(+b.dataset.details));}
function toggleSave(id){state.saved.has(id)?state.saved.delete(id):state.saved.add(id);localStorage.setItem('pour-saved',JSON.stringify([...state.saved]));document.querySelector('#savedCount').textContent=state.saved.size;notify(state.saved.has(id)?'Saved to your collection':'Removed from saved cafés');render()}
function showDetails(id){const c=cafes.find(cafe=>cafe.id===id);document.querySelector('#dialogContent').innerHTML=`<p class="dialog-label">${c.area.toUpperCase()} · ${c.distance} MI AWAY</p><h2>${c.name}</h2><p class="dialog-info">★ ${c.rating} &nbsp; ${c.address}<br>${c.hours}</p><p class="dialog-info">${c.description}</p><div class="dialog-features">${c.tags.map(t=>`<span>${({work:'Laptop friendly',outdoor:'Outdoor seating',roaster:'In-house roaster',brunch:'Brunch'})[t]}</span>`).join('')}</div>`;document.querySelector('#cafeDialog').showModal()}
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
document.querySelector('#searchForm').onsubmit=e=>{e.preventDefault();state.search=document.querySelector('#searchInput').value.trim();state.area=document.querySelector('#neighborhoodSelect').value;state.onlySaved=false;render();document.querySelector('.content-section').scrollIntoView({behavior:'smooth',block:'start'})};document.querySelector('#searchInput').oninput=e=>{state.search=e.target.value;state.onlySaved=false;render()};document.querySelector('#neighborhoodSelect').onchange=e=>{state.area=e.target.value;state.onlySaved=false;render()};document.querySelectorAll('.filter-chip').forEach(button=>button.onclick=()=>{state.filter=button.dataset.filter;state.onlySaved=false;document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('selected',b===button));render()});document.querySelector('#sortSelect').onchange=e=>{state.sort=e.target.value;render()};document.querySelector('#clearButton').onclick=()=>{state.filter='all';state.search='';state.area='all';state.onlySaved=false;document.querySelector('#searchInput').value='';document.querySelector('#neighborhoodSelect').value='all';document.querySelectorAll('.filter-chip').forEach(b=>b.classList.toggle('selected',b.dataset.filter==='all'));render()};document.querySelectorAll('[data-area]').forEach(b=>b.onclick=()=>{state.area=b.dataset.area;state.onlySaved=false;document.querySelector('#neighborhoodSelect').value=state.area;render();document.querySelector('.content-section').scrollIntoView({behavior:'smooth'})});document.querySelector('#nearbyButton').onclick=()=>{state.sort='distance';state.onlySaved=false;document.querySelector('#sortSelect').value='distance';render();notify('Showing cafés closest to you')};document.querySelector('#savedButton').onclick=()=>{if(!state.saved.size)return notify('Save a café to see it here');state.onlySaved=!state.onlySaved;render();notify(state.onlySaved?'Showing your saved cafés':'Showing all cafés');document.querySelector('.content-section').scrollIntoView({behavior:'smooth'})};document.querySelector('.dialog-close').onclick=()=>document.querySelector('#cafeDialog').close();document.querySelector('#expandMap').onclick=()=>notify('Interactive map view coming next — a great API integration for your portfolio.');document.querySelector('#browseAreas').onclick=()=>notify('Choose any neighborhood above to refine the list.');document.querySelector('#savedCount').textContent=state.saved.size;render();
